package:
  name: OpenModelica
  version: 1.25.1

source:
  git: https://github.com/Vincenz0Git/OpenModelica.git
  branch: patch/osx_arm64

build:
  number: 0
  script: | 
    cmake -S . -B $SRC_DIR/../build -Wno-dev \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DCMAKE_C_COMPILER=$CC \
      -DCMAKE_CXX_COMPILER=$CXX \
      -DCMAKE_Fortran_COMPILER=$FC \
      -DOM_ENABLE_GUI_CLIENTS=1 \
      -DCMAKE_PREFIX_PATH=$PREFIX
    cmake --build $SRC_DIR/../build --target install --parallel 4

requirements:
  build: 
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - ccache
    - flex
  host: 
    - openjdk
    - autoconf
    - omniorb
    - flex
    - boost
    - qt
    - qt-webengine
    - qtwebkit
    - openscenegraph
    - lapack
    - blas
    - doxygen
    - sphinx
  run:
    - autoconf
    - omniorb
    - flex
    - boost
    - qt
    - qt-webengine
    - qtwebkit
    - openscenegraph
    - lapack
    - blas
    - doxygen
    - sphinx
    - openjdk
